<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="1.6.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Gear-Database\**" CopyToOutputDirectory="PreserveNewest">
      <Link>Gear-Database\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
    <None Include="secrets.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
